### ISSUE TITLE
Laggy discord

### ISSUE THREAD

**Issue by Mara-Li** [CapnKitten/Translucence#11]
Hey ! Since the discord update of  7/12 (or 8/12), the theme makes my discord very laggy. It's only on this theme (I try with another theme, but not yours).
Could you update it ? :> Thanks !

**Comment by CapnKitten** [comment]
I believe the part making it lag is also the part that adds the blur effect to majority of the popouts, modals, etc. I can see if a workaround will help though.

**Comment by Jnss98b** [comment]
Also, ik that this doesn't really apply to everyone but I find that larger resolution backgrounds make the theme laggier. If you don't really use discord full theme then just keep them at 1080p or even lower. 4k backgrounds crash my discord almost always after a few minutes of usage

**Comment by CapnKitten** [comment]
That's a good find. I'll try it later to see if I can replicate it
