### ISSUE TITLE
Typing indicator not appearing

### ISSUE THREAD

**Issue by solarisodyssey** [CapnKitten/Translucence#12]
When using this theme, the typing indicator at the bottom of channels (just above the message bar) tends to flicker in and out of visibility, usually not appearing at all.

**Comment by CapnKitten** [comment]
Are you using any plugins that may interfere with the typing indicator? I'm able to make it appear every time with no issues.

**Comment by Luke18033** [comment]
I also have this issue, it only happens when the theme is on and the only typing-indicator-modifying plugin I have is BetterRoleColors.

**Comment by CapnKitten** [comment]
Are you using the latest theme version?

**Comment by Luke18033** [comment]
Yeah looks like it

**Comment by CapnKitten** [comment]
Just to be clear, the TypingIndicator dots aren't appearing or the typing bar isn't appearing?

**Comment by Luke18033** [comment]
The entire thing (the animated dots and the "user is typing" text) will flicker in for a second and then vanish. It's not totally consistent, but happens most of the time.

**Comment by CapnKitten** [comment]
I'm still not able to reproduce it. Both the TypingIndicator dots and "user is typing" appear as intended.

**Comment by Luke18033** [comment]
Okay it's caused by CharCounter, using this theme and that plugin together breaks typing indicators. It probably has to do with moving them above the message bar.

**Comment by CapnKitten** [comment]
Aha, finally able to reproduce it. Got it fixed, so all you have to do is restart your Discord client to get it.
