### ISSUE TITLE
Not an issue, just a suggestion

### ISSUE THREAD

**Issue by JJcoms0** [CapnKitten/Translucence#14]
Is it possible to add a parameter such as `--text-highlight-color` which will change the color of highlighted text? 
![discord-suggestion](https://user-images.githubusercontent.com/72825227/107292261-c9179700-6a26-11eb-89a2-5b20b9191010.png)
I have changed all the button colors and was looking for a way to change this to the same color as well.

**Comment by CapnKitten** [comment]
The text selector background uses `--app-accent-rgb` and `--app-accent-text` for the text color.

**Comment by JJcoms0** [comment]
All right. I'll give that a go.

**Comment by JJcoms0** [comment]
the `--app-accent-rgb` worked. Thank you.
