### ISSUE TITLE
discord reply banners and server folder not supported

### ISSUE THREAD

**Issue by FloxY-Y** [CapnKitten/Translucence#18]
everything is in the title ^^

overview :
![discord](https://user-images.githubusercontent.com/47297859/122633783-a125f780-d0da-11eb-9ee7-efb299ba41a4.png)
![image](https://user-images.githubusercontent.com/47297859/122634048-3bd30600-d0dc-11eb-91e1-f4320fb0e48b.png)

ps : discord is a bit boring to always change the class of the web page of the application

**Comment by CapnKitten** [comment]
Both of these have been fixed. Restart your Discord to get the update.

**Comment by FloxY-Y** [comment]
thanks
