### ISSUE TITLE
Emoji info in the reaction picker is blurred except for the server icon

### ISSUE THREAD

**Issue by Jnss98b** [CapnKitten/Translucence#21]
And it's blurred, not just not shown because you can see it being blurred hovering over different emojis
![image](https://user-images.githubusercontent.com/24306400/132976711-b2566593-02df-4121-990b-128fbb61be15.png)

This does not happen in the regular emoji picker in the text field however

**Comment by CapnKitten** [comment]
Fixed this. Restart your Discord client to get the update.
