### ISSUE TITLE
Add 1px bar for window grabbing

### ISSUE THREAD

**Issue by VirusBLITZ** [CapnKitten/Translucence#29]
With recent updates to this awesome theme one important feature was lost:

Compared to Discord's default behaviour Translucence's previous version made it possible to grab the highest pixel of the discord window for quick multitasking, I'd like to see this feature returned or at least have an option to configure it.

would be much appreciated ^^

thanks in advance!

**Comment by CapnKitten** [comment]
I'm not entirely sure what feature you're talking about.

**Comment by VirusBLITZ** [comment]
Oh! I just figured it out lol
I had the plugin channeltabs installed and it messed with the window dragging.
Thanks!
