### ISSUE TITLE
custom CSSs dont work

### ISSUE THREAD

**Issue by Malakasskatakys** [CapnKitten/Translucence#3]
custom CSSs dont work for some reason, i tried to remove the spacing, so i copied the reply you made with the margin command and didnt work, i even copied the example and i got "X" next to the sentences all the time...
![unknown](https://user-images.githubusercontent.com/43682361/95878592-125c2080-0d7e-11eb-8249-3c74b473ef8a.png)
![unknown](https://user-images.githubusercontent.com/43682361/95878925-6ff06d00-0d7e-11eb-9a0e-995945592804.png)

**Comment by CapnKitten** [comment]
That is just the editor giving errors. It doesn't actually affect anything. Just save and update your custom css.
