### ISSUE TITLE
main accent color

### ISSUE THREAD

**Issue by vilchu** [CapnKitten/Translucence#4]
when setting --main-content-color: rgba(0,0,0, 0.7); 

![image](https://user-images.githubusercontent.com/55512609/96039461-58de7780-0e71-11eb-926f-a856a290429e.png)
this happens with the slowmode.

![image](https://user-images.githubusercontent.com/55512609/96039549-7f041780-0e71-11eb-92ff-8c736da810ea.png)
and this with the top thing

**Comment by CapnKitten** [comment]
I have the first one fixed, but the second one isn't a bug. It has no background-color because it's supposed to give off a frosted finish look with the `app-margin`.

**Comment by vilchu** [comment]
O: 
what would be the fix be to the first one? it's more annoying than the second one. uwu

**Comment by CapnKitten** [comment]
I have it fixed, it just isn't live yet. It'll be in the next update.

**Comment by vilchu** [comment]
oh I'm sorry! thanks for the reply uwu

**Comment by CapnKitten** [comment]
All good. Update will be soon because Discord changed a few things.

**Comment by vilchu** [comment]
yay~

**Comment by CapnKitten** [comment]
Update is live.
