### ISSUE TITLE
I removed the bubble around messages but whenever anybody in a server mentions a role that multiple people have or @everyone, it creates a black outline where the bubble used to be, that's unappealing for me.

### ISSUE THREAD

**Issue by radicalwasabi** [CapnKitten/Translucence#5]
[https://imgur.com/a/Lni1mRy](url)

**Comment by CapnKitten** [comment]
There is a body area for issues for a reason; to not have long titles like that. Currently, the mentions border and box-shadow use `--app-accent`, but I can change it to use `--mention-border` instead.

**Comment by radicalwasabi** [comment]
sorry about that, how can I change it?

**Comment by CapnKitten** [comment]
I haven't pushed the update live yet, but it'll be up some time today. I'll let you know when.

**Comment by CapnKitten** [comment]
Update is live. Like I said above, the mentions border and glow will use `--mention-color`.
