### ISSUE TITLE
Any way to make this theme not affect toast notifications?

### ISSUE THREAD

**Issue by swaggyP36000** [CapnKitten/Translucence#6]
For example, with the plugin FriendNotifications, the Toast notifications were Green, Yellow, Red, and Gray for the respective statuses of users, and it is easier to recognize the notifications when they are color coded. This theme seems to force toast notifications to have a black background. Is there a way to make this theme avoid changing toast notifications colors or backgrounds in general?

**Comment by CapnKitten** [comment]
Sorry for the delay. I can make it so it doesn't alter the background for those types of notifications. It'll be with the next update.
