### ISSUE TITLE
Just Some Glitches

### ISSUE THREAD

**Issue by Malakasskatakys** [CapnKitten/Translucence#8]
the speaking indicator colour is broken, also some buttons look like 2nd picture...
![unknown](https://user-images.githubusercontent.com/43682361/99041769-35077200-2594-11eb-9372-0549df63a40b.png)
![unknown](https://user-images.githubusercontent.com/43682361/99041781-3afd5300-2594-11eb-84f1-d9a99113d6a8.png)

**Comment by CapnKitten** [comment]
Got them fixed and will be in the next update, thanks.
